version: '3.1'

services:

  frontier:
    image: crawlercommons/url-frontier:0.2  
    container_name: frontier
    command: rocksdb.path=/crawldir/rocksdb
    ports:
      - 7071:7071
    volumes:
      - data01:/crawldir

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - data02:/usr/share/elasticsearch/data

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

volumes:
  data01:
    driver: local
  data02:
    driver: local


